/*
 * Flipdish Open API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipdish.apiclient.api;

import com.flipdish.apiclient.ApiException;
import com.flipdish.apiclient.model.AccountDetailBase;
import com.flipdish.apiclient.model.ChangePasswordModel;
import com.flipdish.apiclient.model.CreateAccountModel;
import com.flipdish.apiclient.model.LoginModel;
import com.flipdish.apiclient.model.LoginWithPinModel;
import com.flipdish.apiclient.model.PasswordResetModel;
import com.flipdish.apiclient.model.RequestLoginPinModel;
import com.flipdish.apiclient.model.RequestLoginPinResposne;
import com.flipdish.apiclient.model.RequestPasswordResetModel;
import com.flipdish.apiclient.model.RestApiArrayResultLocalisedTimeZone;
import com.flipdish.apiclient.model.RestApiErrorResult;
import com.flipdish.apiclient.model.RestApiForbiddenResult;
import com.flipdish.apiclient.model.RestApiResultAccountDetail;
import com.flipdish.apiclient.model.RestApiUnauthorizedResult;
import com.flipdish.apiclient.model.SetPasswordWithPinModel;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountsApi
 */
@Ignore
public class AccountsApiTest {

    private final AccountsApi api = new AccountsApi();

    
    /**
     * Answer a signup question
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void answerSignUpQuestionTest() throws ApiException {
        String signupStepAction = null;
        Integer answerId = null;
        api.answerSignUpQuestion(signupStepAction, answerId);

        // TODO: test validations
    }
    
    /**
     * Change password
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void changePasswordTest() throws ApiException {
        ChangePasswordModel changePasswordModel = null;
        api.changePassword(changePasswordModel);

        // TODO: test validations
    }
    
    /**
     * Change password
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void changePasswordWithPinTest() throws ApiException {
        SetPasswordWithPinModel changePasswordModel = null;
        api.changePasswordWithPin(changePasswordModel);

        // TODO: test validations
    }
    
    /**
     * Create account with email address and store name
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAccountTest() throws ApiException {
        CreateAccountModel createAccountModel = null;
        api.createAccount(createAccountModel);

        // TODO: test validations
    }
    
    /**
     * Gets the current account detail
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountDetailsTest() throws ApiException {
        RestApiResultAccountDetail response = api.getAccountDetails();

        // TODO: test validations
    }
    
    /**
     * [PRIVATE API] Get timezones localised to users language
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLocalisedTimeZonesTest() throws ApiException {
        RestApiArrayResultLocalisedTimeZone response = api.getLocalisedTimeZones();

        // TODO: test validations
    }
    
    /**
     * Login with username and password
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void loginTest() throws ApiException {
        LoginModel loginModel = null;
        api.login(loginModel);

        // TODO: test validations
    }
    
    /**
     * Login with username and password
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void loginWithPinTest() throws ApiException {
        LoginWithPinModel loginModel = null;
        api.loginWithPin(loginModel);

        // TODO: test validations
    }
    
    /**
     * Log out. It removes Flipdish authorization Cookie.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void logoutTest() throws ApiException {
        api.logout();

        // TODO: test validations
    }
    
    /**
     * Reset password with token.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void passwordResetWithTokenTest() throws ApiException {
        PasswordResetModel passwordResetModel = null;
        api.passwordResetWithToken(passwordResetModel);

        // TODO: test validations
    }
    
    /**
     * Request login PIN. The server sends the PIN to the email address.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void requestLoginPinTest() throws ApiException {
        RequestLoginPinModel requestLoginPinRequest = null;
        RequestLoginPinResposne response = api.requestLoginPin(requestLoginPinRequest);

        // TODO: test validations
    }
    
    /**
     * Request password reset. Flipdish system will send a token via email.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void requestPasswordResetTest() throws ApiException {
        RequestPasswordResetModel requestPasswordResetModel = null;
        api.requestPasswordReset(requestPasswordResetModel);

        // TODO: test validations
    }
    
    /**
     * Skip a signup question
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void skipSignupStepTest() throws ApiException {
        String signupStepAction = null;
        api.skipSignupStep(signupStepAction);

        // TODO: test validations
    }
    
    /**
     * Update account with name and language
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateAccountTest() throws ApiException {
        AccountDetailBase updateAccountModel = null;
        api.updateAccount(updateAccountModel);

        // TODO: test validations
    }
    
}
