/*
 * Flipdish Open API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipdish.apiclient.api;

import com.flipdish.apiclient.ApiException;
import com.flipdish.apiclient.model.DriverLoginModel;
import com.flipdish.apiclient.model.DriverRequestLoginPinModel;
import com.flipdish.apiclient.model.RestApiArrayResultDriverStore;
import com.flipdish.apiclient.model.RestApiErrorResult;
import com.flipdish.apiclient.model.RestApiForbiddenResult;
import com.flipdish.apiclient.model.RestApiResultDriver;
import com.flipdish.apiclient.model.RestApiStringResult;
import com.flipdish.apiclient.model.RestApiUnauthorizedResult;
import com.flipdish.apiclient.model.UpdateDriverNotificationToken;
import com.flipdish.apiclient.model.UpdateDriverProfileModel;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DriversApi
 */
@Ignore
public class DriversApiTest {

    private final DriversApi api = new DriversApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addDriverNotificationTokenTest() throws ApiException {
        UpdateDriverNotificationToken updateDriverToken = null;
        api.addDriverNotificationToken(updateDriverToken);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteDriverProfileImageTest() throws ApiException {
        api.deleteDriverProfileImage();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void driverLoginTest() throws ApiException {
        DriverLoginModel driverLoginModel = null;
        api.driverLogin(driverLoginModel);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void driverRequestLoginCodeSmsTest() throws ApiException {
        DriverRequestLoginPinModel driverRequestLoginPinModel = null;
        api.driverRequestLoginCodeSms(driverRequestLoginPinModel);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDriverProfileTest() throws ApiException {
        RestApiResultDriver response = api.getDriverProfile();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStoresForDriverTest() throws ApiException {
        RestApiArrayResultDriverStore response = api.getStoresForDriver();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeDriverNotificationTokenTest() throws ApiException {
        UpdateDriverNotificationToken removeDriverToken = null;
        api.removeDriverNotificationToken(removeDriverToken);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void setDriverPresenceForStoreTest() throws ApiException {
        Integer storeId = null;
        String presence = null;
        api.setDriverPresenceForStore(storeId, presence);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void setDriverProfileImageTest() throws ApiException {
        RestApiStringResult response = api.setDriverProfileImage();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateDeliveryTrackingStatusTest() throws ApiException {
        Integer orderId = null;
        String deliveryTrackingStatus = null;
        RestApiStringResult response = api.updateDeliveryTrackingStatus(orderId, deliveryTrackingStatus);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateDriverProfileTest() throws ApiException {
        UpdateDriverProfileModel updateDriverProfile = null;
        api.updateDriverProfile(updateDriverProfile);

        // TODO: test validations
    }
    
}
