/*
 * Flipdish Open API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipdish.apiclient.api;

import com.flipdish.apiclient.model.OnboardingConfigUpdate;
import com.flipdish.apiclient.model.OnboardingItemUpdate;
import com.flipdish.apiclient.model.RestApiArrayResultOnboardingConfig;
import com.flipdish.apiclient.model.RestApiErrorResult;
import com.flipdish.apiclient.model.RestApiForbiddenResult;
import com.flipdish.apiclient.model.RestApiResultOnboardingConfig;
import com.flipdish.apiclient.model.RestApiResultOnboardingProcess;
import com.flipdish.apiclient.model.RestApiUnauthorizedResult;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OnboardingApi
 */
@Ignore
public class OnboardingApiTest {

    private final OnboardingApi api = new OnboardingApi();

    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getOnboardingConfigTest() throws Exception {
        String appId = null;
        RestApiResultOnboardingConfig response = api.getOnboardingConfig(appId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getOnboardingConfigsTest() throws Exception {
        String appId = null;
        RestApiArrayResultOnboardingConfig response = api.getOnboardingConfigs(appId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getOnboardingItemsTest() throws Exception {
        String appId = null;
        Integer storeId = null;
        Integer milestoneId = null;
        RestApiResultOnboardingProcess response = api.getOnboardingItems(appId, storeId, milestoneId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getOnboardingItemsV2Test() throws Exception {
        String appId = null;
        Integer storeId = null;
        Integer milestoneId = null;
        RestApiResultOnboardingProcess response = api.getOnboardingItemsV2(appId, storeId, milestoneId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateOnboardingConfigTest() throws Exception {
        String appId = null;
        OnboardingConfigUpdate configUpdate = null;
        api.updateOnboardingConfig(appId, configUpdate);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateOnboardingConfigByIdTest() throws Exception {
        String appId = null;
        Integer configId = null;
        OnboardingConfigUpdate configUpdate = null;
        api.updateOnboardingConfigById(appId, configId, configUpdate);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateOnboardingItemTest() throws Exception {
        String appId = null;
        Integer storeId = null;
        Integer onboardingItemId = null;
        OnboardingItemUpdate itemUpdate = null;
        api.updateOnboardingItem(appId, storeId, onboardingItemId, itemUpdate);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateOnboardingItemV2Test() throws Exception {
        String appId = null;
        Integer onboardingItemId = null;
        OnboardingItemUpdate itemUpdate = null;
        Integer storeId = null;
        api.updateOnboardingItemV2(appId, onboardingItemId, itemUpdate, storeId);

        // TODO: test validations
    }
    
}
