/*
 * Flipdish Open API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipdish.apiclient.api;

import com.flipdish.apiclient.ApiException;
import com.flipdish.apiclient.model.Accept;
import org.threeten.bp.OffsetDateTime;
import com.flipdish.apiclient.model.Refund;
import com.flipdish.apiclient.model.Reject;
import com.flipdish.apiclient.model.RestApiErrorResult;
import com.flipdish.apiclient.model.RestApiForbiddenResult;
import com.flipdish.apiclient.model.RestApiPaginationResultOrder;
import com.flipdish.apiclient.model.RestApiPaginationResultOrderSummary;
import com.flipdish.apiclient.model.RestApiResultOrder;
import com.flipdish.apiclient.model.RestApiUnauthorizedResult;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OrdersApi
 */
@Ignore
public class OrdersApiTest {

    private final OrdersApi api = new OrdersApi();

    
    /**
     * Accept order
     *
     * To accept an order, you create an &#x60;accept&#x60; object and send it to Flipdish API using HTTP POST method. &#x60;Id&#x60; path parameter identifies the order.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void acceptOrderTest() throws ApiException {
        Integer id = null;
        Accept acceptObject = null;
        api.acceptOrder(id, acceptObject);

        // TODO: test validations
    }
    
    /**
     * Dispatch order
     *
     * To dispatch an order send a POST request with &#x60;Id&#x60; path parameter which identifies the order.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void dispatchOrderTest() throws ApiException {
        Integer id = null;
        api.dispatchOrder(id);

        // TODO: test validations
    }
    
    /**
     * Get order by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getOrderByIdTest() throws ApiException {
        Integer id = null;
        RestApiResultOrder response = api.getOrderById(id);

        // TODO: test validations
    }
    
    /**
     * Get orders by filter
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getOrdersTest() throws ApiException {
        List<Integer> physicalRestaurantId = null;
        List<String> state = null;
        OffsetDateTime from = null;
        OffsetDateTime to = null;
        Integer page = null;
        Integer limit = null;
        RestApiPaginationResultOrder response = api.getOrders(physicalRestaurantId, state, from, to, page, limit);

        // TODO: test validations
    }
    
    /**
     * [PRIVATE API] Get summary of orders by filter
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getOrdersSummaryTest() throws ApiException {
        String appId = null;
        String searchQuery = null;
        List<Integer> physicalRestaurantId = null;
        List<String> state = null;
        Integer page = null;
        Integer limit = null;
        Boolean orderByRequestedForTime = null;
        RestApiPaginationResultOrderSummary response = api.getOrdersSummary(appId, searchQuery, physicalRestaurantId, state, page, limit, orderByRequestedForTime);

        // TODO: test validations
    }
    
    /**
     * Refund order
     *
     * To refund an order, you create a &#x60;refund&#x60; object and send it to Flipdish API using HTTP POST method. &#x60;Id&#x60; path parameter identifies the order.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void refundOrderTest() throws ApiException {
        Integer id = null;
        Refund refundObject = null;
        api.refundOrder(id, refundObject);

        // TODO: test validations
    }
    
    /**
     * Reject order
     *
     * To reject an order, you create a &#x60;reject&#x60; object and send it to Flipdish API using HTTP POST method. &#x60;Id&#x60; path parameter identifies the order.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void rejectOrderTest() throws ApiException {
        Integer id = null;
        Reject rejectObject = null;
        api.rejectOrder(id, rejectObject);

        // TODO: test validations
    }
    
}
