/*
 * Flipdish Open API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipdish.apiclient.api;

import com.flipdish.apiclient.model.RestApiErrorResult;
import com.flipdish.apiclient.model.RestApiForbiddenResult;
import com.flipdish.apiclient.model.RestApiResultStoreOrderCapacityConfig;
import com.flipdish.apiclient.model.RestApiUnauthorizedResult;
import com.flipdish.apiclient.model.StoreOrderCapacityConfigEditModel;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StoreOrderCapacityApi
 */
@Ignore
public class StoreOrderCapacityApiTest {

    private final StoreOrderCapacityApi api = new StoreOrderCapacityApi();

    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getStoreOrderCapacityTest() throws Exception {
        String appId = null;
        Integer storeId = null;
        String deliveryType = null;
        RestApiResultStoreOrderCapacityConfig response = api.getStoreOrderCapacity(appId, storeId, deliveryType);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateStoreOrderCapacityConfigTest() throws Exception {
        Integer storeId = null;
        String deliveryType = null;
        StoreOrderCapacityConfigEditModel newOrderCapacityConfig = null;
        String appId = null;
        api.updateStoreOrderCapacityConfig(storeId, deliveryType, newOrderCapacityConfig, appId);

        // TODO: test validations
    }
    
}
